name: Github CI
on:
  push:
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Cache pipenv virtualenvs
        id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies (incl. dev)
        run: |
          pipenv install --dev --deploy
          pipenv --venv
          pipenv run python -V
          pipenv run pip -V

      - name: Run test suite
        run: |
          pipenv run invoke tests --env=ci --tags=smoke --rerun=1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./report/
          retention-days: 7